repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/

releases:
  - name: metallb
    installed: ${metallb_enabled}
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: ${metallb_version}

  - name: ingress-nginx
    installed: ${nginx_ingress_enabled}
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: ${nginx_ingress_version}
    values:
      - controller:
          service:
            type: LoadBalancer
    %{ if nginx_ingress_loadbalancer_ip != null ~}
        loadBalancerIP: ${nginx_ingress_loadbalancer_ip}
    %{ endif ~}

  - name: nfs-subdir-external-provisioner
    installed: ${nfs_storage_enabled}
    namespace: storage
    createNamespace: true
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: ${nfs_storage_version}
    values:
      - nfs:
          server: ${nfs_storage_server}
          path: ${nfs_storage_path}

        storageClass:
          name: ${nfs_storage_class}
          defaultClass: ${nfs_storage_default_class}

  - name: headlamp
    installed: ${headlamp_enabled}
    namespace: headlamp
    createNamespace: true
    chart: headlamp/headlamp
    version: ${headlamp_version}
    values:
      - service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: ${headlamp_hostname}
              paths:
                - path: /
                  type: Prefix
